call plug#begin("~/.local/share/nvim/site/autoload/plug.vim")
 Plug 'https://github.com/Yggdroot/indentLine'
 Plug 'https://github.com/ap/vim-buftabline'
 Plug 'https://github.com/iamcco/markdown-preview.nvim'
 Plug 'https://github.com/justinmk/vim-dirvish'
 Plug 'https://github.com/neovim/nvim-lspconfig'
 Plug 'https://github.com/ntpeters/vim-better-whitespace'
 Plug 'https://github.com/ntpeters/vim-better-whitespace'
 Plug 'https://github.com/puremourning/vimspector'
call plug#end()
